
% important parameters that need data-dependent cross-validation:

lklhd_cond_mindiff = -0.1; % float value; a reasonable range is [-0.2 0.2]
K_default = 5; % integer value; a reasonable range is [2 20]


% convergence parameters that define a trade-off between better
% accurracy and run-time:
EM_restarts = 3;
mindiff = 1e-3;
maxcount = 100;

% plot parameters; turn on only if you want to visually inspect the
% training:
plot_graph = true;
plot_lklhd_diff = true;


% less important parameters, just leave as they are:
dispevery = 500;
find_best_K = false;
recursive_EM_after_struct_change = 0;
recursuve_EM_after_new_closed = 1;
recursuve_EM_final = 0;
plot_EM = 0;
lklhd_cond_single = false;

history_keep = true;
strategy = 'combine closed';
focus_dim = [];
no_new_hidden_nodes = false;

close_last_first = false;
lower_layers_first = true;
combine_observed_first = false;

minscore = 0.001;

% Experimental: Set the expected distribution of the output classes to
% uniform. This might help in the case of un-balanced training classes.
balance_classes = false;

% create model
model_hpmm2 = hpmm2.graph(...
    'mindiff',1e-6,...
    'K_default',K_default,...
    'maxcount',maxcount,...
    'mindiff',mindiff,...
    'dispevery',dispevery,...
    'find_best_K',find_best_K,...
    'lklhd_cond_mindiff',lklhd_cond_mindiff,...
    'recursive_EM_after_struct_change',recursive_EM_after_struct_change,...
    'recursuve_EM_after_new_closed',recursuve_EM_after_new_closed,...
    'recursuve_EM_final',recursuve_EM_final,...
    'plot_graph',plot_graph,...
    'plot_lklhd_diff',plot_lklhd_diff,...
    'plot_EM',plot_EM,...
    'strategy',strategy,...
    'focus_dim',focus_dim,...
    'no_new_hidden_nodes',no_new_hidden_nodes,...
    'lklhd_cond_single',lklhd_cond_single,...
    'EM_restarts',EM_restarts,...
    'close_last_first',close_last_first,...
    'lower_layers_first',lower_layers_first,...
    'combine_observed_first',combine_observed_first,...
    'history_keep',history_keep,...
    'minscore', minscore,...
    'balance_classes', balance_classes);

% if this is set to true, we learn a simple mixture model by having a
% single hidden node
% model_hpmm2.no_new_hidden_nodes = true;

% this sets the new graph_perclass model. The ind_class parameter is
% important, it selects for which class we built multiple trees.
% model_hpmm2 = hpmm2.graph_perclass('ind_class', 9, 'graph', model_hpmm2);  
